### ISSUE TITLE
总结下我在mac使用出现的问题（python3)

### ISSUE THREAD

**Issue by mggger** [laixintao/jupyter-dot-kernel#1]
- 启动notebook后， kernel选择里面没有dot
1. cd /Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/kernels/ (这个路径可以通过sudo find / -name 'kernel.json') 获取到
2. mkdir dot
3. 将kernel.json 复制到dot文件夹里面 或者自己创建kernel.json,  内容为
    {           
        "argv": ["python3", "-m", "dot_kernel", "-f", "{connection_file}"],
        "display_name": "dot"
    }        
- 使用过程没有graphviz报错 
brew install graphviz

**Comment by laixintao** [comment]
问题1，谢谢，kernel 是需要安装的。因为我自己开发的时候执行过命令安装，后来写文档的时候给忘记这一步了 😂 

> Now create a JSON kernel spec file and install it using `jupyter kernelspec install </path/to/kernel>`. Place your kernel module anywhere Python can import it (try current directory for testing). Finally, you can run your kernel using jupyter console --kernel <mykernelname>. Note that <mykernelname> in the below example is echo.

https://jupyter-client.readthedocs.io/en/stable/wrapperkernels.html

我看看能不能加在 setup.py 里面，不能我就更新下文档吧。

**Comment by laixintao** [comment]
添加了一个脚本，我看其他的 kernel 也是这么做的。  有兴趣的话可以再试试
