### ISSUE TITLE
How to install the kernel

### ISSUE THREAD

**Issue by keyu-Li** [laixintao/jupyter-dot-kernel#16]
I am not clear how to run this step “install-dot-kernel”

**Comment by laixintao** [comment]
Hi did you run `pip install dot_kernel` ?

After this command you will get a `install-dot-kernel` command available in you $PATH, just type it and hit Enter should work.

**Comment by keyu-Li** [comment]
Sorry I still cannot execute this command. I installed it under windows system. And I found the "install-dot-kernel" file in my anaconda environment. How can I execute it?

**Comment by laixintao** [comment]
Sorry I don't use windows. Can you try to execute via full path (absolute
path) ?

**Comment by keyu-Li** [comment]
Unfortunately this doesn't work. It is not an executable file for windows. And I don't know how to execute non-executable file script under windows system. I think maybe I can solve the problem in another way, such as using ubuntu system. Thank you for your attention to this issue.

**Comment by laixintao** [comment]
The command `[install-dot-kernel](https://github.com/laixintao/jupyter-dot-kernel/blob/master/bin/install-dot-kernel)` simply run `jupyter kernelspec install --use dot_kernel_spec`, can you find where is your dot_kernel_spec and run this command manually?
