### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by alexxxmg** [laixintao/jupyter-dot-kernel#4]
hello,
I was very interested in trying this, on my machine:
**Linux lambda 4.15.10-300.fc27.x86_64 #1 SMP Thu Mar 15 17:13:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Fedora release 27** 

but after a **pip install dot_kernel** without issues,
the command **install-dot-kernel** returns this:

```
Traceback (most recentTraceback (most recent call last):
  File "/usr/bin/jupyter-kernelspec", line 11, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "/usr/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python2.7/site-packages/jupyter_client/kernelspecapp.py", line 273, in start
    return self.subapp.start()
  File "/usr/lib/python2.7/site-packages/jupyter_client/kernelspecapp.py", line 143, in start
    replace=self.replace,
  File "/usr/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 346, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/usr/lib64/python2.7/shutil.py", line 185, in copytree
    names = os.listdir(src)
```

do you have any ideas?

**Comment by SmirkCao** [comment]
- git clone https://github.com/laixintao/jupyter-dot-kernel.git
- cd jupyter-dot-kernel
- jupyter kernelspec install dot_kernel_spec --user

**Comment by alexxxmg** [comment]
thank you for your help!
the last command gives me
`[InstallKernelSpec] Installed kernelspec dot_kernel_spec in /root/.local/share/jupyter/kernels/dot_kernel_spec`

and when I launch jupyter I see and can select a dot file type.
Bur running anything, as the simple test command `digraph {
    label = "abc";
    a -> b;
}`,
I get the following at the console:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/lib/python2.7/site-packages/dot_kernel/kernel.py", line 29, in do_execute
    data = urllib.parse.quote(base64.b64encode(png_src))
AttributeError: 'module' object has no attribute 'parse'
```

**Comment by SmirkCao** [comment]
try this
```
sudo pip install 'prompt-toolkit==1.0.15'
```

**Comment by alexxxmg** [comment]
damn, no, I'm sorry...
I get exactly the same error!

**Comment by SmirkCao** [comment]
Oh, sorry.
python3 dependence
emmm..
visit the following link:
https://docs.python.org/2/library/urlparse.html
may you use python3 or change the source code for using **urlparse**

**Comment by alexxxmg** [comment]
urlparse ? I checked and I have it installed...
use python3 ? ok, but where?

**Comment by SmirkCao** [comment]
- may you check this link for using python3
https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3
- or modify the following code segment in "kernel.py" line 33 under python 2 env. I think...
```python
 data = urllib.parse.quote(base64.b64encode(png_src))
```
replace "urlib.parse" with "urlparse" API, and you need some test.

**Comment by alexxxmg** [comment]
some progress, thanks to you! But not there yet...
I added `from urlparse import urlparse`

and changed  the urllib call to `data = urlparse(base64.b64encode(png_src))`

Now I get no error at the dot commands execution, but the output is a small _broken image_ icon

**Comment by laixintao** [comment]
Any updates? Can you try it in a docker? Then I can reproduce it.

I am going to close now, I fix some package problems, can you try again?

Feel free to reopen it if you have further questions.
